# Generated by Django 6.0.3 on 2026-05-23 08:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_no", models.CharField(max_length=32, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("department", models.CharField(max_length=100)),
                ("project_code", models.CharField(blank=True, max_length=100)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("sample_received", "Sample Received"),
                            ("wip_created", "WIP Created"),
                            ("dispatched", "Dispatched"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=40,
                    ),
                ),
                ("material_type", models.CharField(default="Silicon", max_length=100)),
                ("target_measurement", models.CharField(blank=True, max_length=255)),
                (
                    "expected_output_format",
                    models.CharField(blank=True, max_length=120),
                ),
                ("special_instruction", models.TextField(blank=True)),
                ("safety_rules_confirmed", models.BooleanField(default=False)),
                ("required_completion_date", models.DateField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("manager_comment", models.TextField(blank=True)),
            ],
            options={
                "db_table": "commission_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="request-attachments/")),
                ("label", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "db_table": "request_attachment",
            },
        ),
        migrations.CreateModel(
            name="RequestStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("previous_status", models.CharField(blank=True, max_length=40)),
                ("new_status", models.CharField(max_length=40)),
                ("reason", models.TextField(blank=True)),
            ],
            options={
                "db_table": "request_status_history",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sample_no", models.CharField(max_length=32, unique=True)),
                ("sample_name", models.CharField(max_length=255)),
                ("lot_id", models.CharField(max_length=100)),
                ("wafer_id", models.CharField(blank=True, max_length=100)),
                ("material_type", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("description", models.TextField(blank=True)),
                ("handling_notes", models.TextField(blank=True)),
                ("holding_area", models.CharField(blank=True, max_length=120)),
                ("condition", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_receive", "Pending Receive"),
                            ("received", "Received"),
                            ("waiting_wip", "Waiting WIP"),
                            ("in_wip", "In WIP"),
                            ("dispatched", "Dispatched"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("returned", "Returned"),
                            ("scrapped", "Scrapped"),
                        ],
                        default="pending_receive",
                        max_length=40,
                    ),
                ),
                ("received_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "sample",
            },
        ),
        migrations.CreateModel(
            name="SampleStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("previous_status", models.CharField(blank=True, max_length=40)),
                ("new_status", models.CharField(max_length=40)),
                ("reason", models.TextField(blank=True)),
            ],
            options={
                "db_table": "sample_status_history",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("more_info", "More Information"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "priority_override",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "approval_record",
                "ordering": ["-created_at"],
            },
        ),
    ]
