# Generated by Django 6.0.3 on 2026-05-23 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commissions", "0001_initial"),
        ("equipment", "0001_initial"),
        ("experiments", "0001_initial"),
        ("wip", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrecord",
            name="suggested_recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="equipment.recipe",
            ),
        ),
        migrations.AddField(
            model_name="commissionrequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_commission_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commissionrequest",
            name="experiment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requests",
                to="experiments.experimenttype",
            ),
        ),
        migrations.AddField(
            model_name="commissionrequest",
            name="preferred_recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_by_requests",
                to="equipment.recipe",
            ),
        ),
        migrations.AddField(
            model_name="commissionrequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commission_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvalrecord",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_records",
                to="commissions.commissionrequest",
            ),
        ),
        migrations.AddField(
            model_name="requestattachment",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="commissions.commissionrequest",
            ),
        ),
        migrations.AddField(
            model_name="requestattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="requeststatushistory",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="requeststatushistory",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="commissions.commissionrequest",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="current_wip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_samples",
                to="wip.wipbatch",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_samples",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="samples",
                to="commissions.commissionrequest",
            ),
        ),
        migrations.AddField(
            model_name="samplestatushistory",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="samplestatushistory",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="commissions.sample",
            ),
        ),
        migrations.AddIndex(
            model_name="commissionrequest",
            index=models.Index(
                fields=["requester", "status"], name="commission__request_d2c5d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commissionrequest",
            index=models.Index(
                fields=["status", "priority"], name="commission__status_97ff58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commissionrequest",
            index=models.Index(
                fields=["required_completion_date"],
                name="commission__require_6425c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(
                fields=["request", "status"], name="sample_request_8356ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(
                fields=["status", "material_type"], name="sample_status_39aa84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(fields=["sample_no"], name="sample_sample__080537_idx"),
        ),
    ]
