# Generated by Django 6.0.3 on 2026-05-23 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_workflow_statuses(apps, schema_editor):
    CommissionRequest = apps.get_model("commissions", "CommissionRequest")
    Sample = apps.get_model("commissions", "Sample")
    request_map = {
        "pending_approval": "waiting_approval",
        "sample_received": "received",
        "wip_created": "in_wip",
        "dispatched": "queued",
        "failed": "final_check",
    }
    sample_map = {
        "waiting_wip": "received",
        "dispatched": "queued",
        "returned": "rejected",
        "scrapped": "failed",
    }
    for old, new in request_map.items():
        CommissionRequest.objects.filter(status=old).update(status=new)
    for old, new in sample_map.items():
        Sample.objects.filter(status=old).update(status=new)


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="commissionrequest",
            name="assigned_lab_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_commission_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="commissionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("waiting_approval", "Waiting Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("waiting_sample_receive", "Waiting for Sample Receive"),
                    ("received", "Received"),
                    ("in_wip", "In WIP"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("final_check", "Final Check"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_receive", "Pending Receive"),
                    ("received", "Received"),
                    ("rejected", "Rejected"),
                    ("in_wip", "In WIP"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending_receive",
                max_length=40,
            ),
        ),
        migrations.RunPython(migrate_workflow_statuses, migrations.RunPython.noop),
    ]
