# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0004_sampleexperiment"),
    ]

    operations = [
        migrations.AddField(
            model_name="commissionrequest",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="commissionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("waiting_approval", "Waiting Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("waiting_sample_receive", "Waiting for Sample Receive"),
                    ("received", "Received"),
                    ("in_wip", "In WIP"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("final_check", "Final Check"),
                    ("completed", "Completed"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=40,
            ),
        ),
    ]
