# Generated by Django 6.0.3 on 2026-05-23 08:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("level", models.CharField(default="info", max_length=20)),
                ("message", models.TextField()),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "dispatch_log",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DispatchStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="pending", max_length=40)),
                ("progress", models.FloatField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "dispatch_step",
                "ordering": ["sequence", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="DispatchJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dispatch_no", models.CharField(max_length=32, unique=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("assigned", "Assigned"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=40,
                    ),
                ),
                ("progress", models.FloatField(default=0)),
                ("current_step", models.CharField(blank=True, max_length=255)),
                ("worker_node", models.CharField(blank=True, max_length=120)),
                ("queue_name", models.CharField(blank=True, max_length=120)),
                ("queue_position", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("simulate_failure", models.BooleanField(default=False)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_dispatch_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dispatch_job",
                "ordering": ["-created_at"],
            },
        ),
    ]
