# Generated by Django 6.0.3 on 2026-05-23 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dispatch", "0001_initial"),
        ("equipment", "0001_initial"),
        ("wip", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchjob",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispatch_jobs",
                to="equipment.equipment",
            ),
        ),
        migrations.AddField(
            model_name="dispatchjob",
            name="wip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispatches",
                to="wip.wipbatch",
            ),
        ),
        migrations.AddField(
            model_name="dispatchlog",
            name="dispatch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="dispatch.dispatchjob",
            ),
        ),
        migrations.AddField(
            model_name="dispatchstep",
            name="dispatch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="dispatch.dispatchjob",
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchjob",
            index=models.Index(
                fields=["status", "created_at"], name="dispatch_jo_status_e46d24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchjob",
            index=models.Index(
                fields=["wip", "status"], name="dispatch_jo_wip_id_208f42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchjob",
            index=models.Index(
                fields=["equipment", "status"], name="dispatch_jo_equipme_ad0085_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchlog",
            index=models.Index(
                fields=["dispatch", "created_at"], name="dispatch_lo_dispatc_ad2953_idx"
            ),
        ),
    ]
