# Generated by Django 6.0.3 on 2026-05-23 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchjob",
            name="final_confirmation_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dispatchjob",
            name="final_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispatchjob",
            name="final_confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="final_confirmed_dispatch_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
