# Generated by Django 6.0.3 on 2026-05-23 08:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dispatch", "0001_initial"),
        ("experiments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("queue_name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "equipment_type",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("equipment_code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("model_name", models.CharField(max_length=200)),
                ("worker_queue_name", models.CharField(max_length=120)),
                ("worker_node_name", models.CharField(blank=True, max_length=120)),
                ("capacity", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("reserved", "Reserved"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("maintenance", "Maintenance"),
                            ("offline", "Offline"),
                            ("error", "Error"),
                        ],
                        default="idle",
                        max_length=30,
                    ),
                ),
                ("current_step", models.CharField(blank=True, max_length=255)),
                ("progress", models.FloatField(default=0)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("completed_count_today", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "current_dispatch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_on_equipment",
                        to="dispatch.dispatchjob",
                    ),
                ),
                (
                    "equipment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment",
                        to="equipment.equipmenttype",
                    ),
                ),
            ],
            options={
                "db_table": "equipment",
                "ordering": ["equipment_code"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recipe_code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("estimated_runtime_sec", models.PositiveIntegerField(default=60)),
                ("max_batch_size", models.PositiveIntegerField(default=10)),
                ("material_constraints", models.JSONField(blank=True, default=dict)),
                ("safety_constraints", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipes",
                        to="equipment.equipmenttype",
                    ),
                ),
                (
                    "experiment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipes",
                        to="experiments.experimenttype",
                    ),
                ),
            ],
            options={
                "db_table": "recipe",
                "ordering": ["recipe_code"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentCapability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capability_links",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_capabilities",
                        to="equipment.recipe",
                    ),
                ),
            ],
            options={
                "db_table": "equipment_capability",
            },
        ),
        migrations.CreateModel(
            name="EquipmentEventLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=80)),
                ("message", models.TextField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "dispatch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_events",
                        to="dispatch.dispatchjob",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_logs",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "db_table": "equipment_event_log",
                "indexes": [
                    models.Index(
                        fields=["equipment", "created_at"],
                        name="equipment_e_equipme_b4483b_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["status", "is_active"], name="equipment_status_74961f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["equipment_type", "status"], name="equipment_equipme_4c1e6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["experiment_type", "equipment_type", "is_active"],
                name="recipe_experim_2f3dbd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["recipe_code"], name="recipe_recipe__a99477_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="equipmentcapability",
            unique_together={("equipment", "recipe")},
        ),
    ]
