# Generated by Django 6.0.3 on 2026-05-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmenttype",
            name="queue_name",
            field=models.CharField(max_length=120),
        ),
    ]
