# Generated by Django 6.0.3 on 2026-05-23 16:11

from django.db import migrations, models


def migrate_equipment_statuses(apps, schema_editor):
    Equipment = apps.get_model("equipment", "Equipment")
    status_map = {
        "reserved": "idle",
        "queued": "working",
        "running": "working",
        "error": "faulty",
    }
    for old, new in status_map.items():
        Equipment.objects.filter(status=old).update(status=new)


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0002_alter_equipmenttype_queue_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("working", "Working"),
                    ("faulty", "Faulty"),
                    ("maintenance", "Maintenance"),
                    ("offline", "Offline"),
                ],
                default="idle",
                max_length=30,
            ),
        ),
        migrations.RunPython(migrate_equipment_statuses, migrations.RunPython.noop),
    ]
