# Generated by Django 6.0.3 on 2026-05-23 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalize_lab_member_roles(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    UserProfile.objects.filter(role="lab_member").update(role="lab_user")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("fab_user", "Fab User"),
                    ("lab_user", "Lab User"),
                    ("lab_member", "Lab Member (legacy)"),
                    ("lab_manager", "Lab Manager"),
                    ("admin", "Admin"),
                ],
                default="fab_user",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_context", models.CharField(blank=True, max_length=40)),
                ("notification_type", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=180)),
                ("body", models.TextField(blank=True)),
                ("related_entity_type", models.CharField(blank=True, max_length=80)),
                ("related_entity_id", models.CharField(blank=True, max_length=80)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "created_at"],
                        name="notificatio_recipie_779c41_idx",
                    ),
                    models.Index(
                        fields=["related_entity_type", "related_entity_id"],
                        name="notificatio_related_5348f6_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(normalize_lab_member_roles, migrations.RunPython.noop),
    ]
