# Generated by Django 6.0.3 on 2026-05-23 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_wip_statuses(apps, schema_editor):
    WipBatch = apps.get_model("wip", "WipBatch")
    status_map = {
        "created": "draft",
        "queued": "ready_for_dispatch",
        "dispatched": "dispatching",
        "partially_completed": "completed",
    }
    for old, new in status_map.items():
        WipBatch.objects.filter(status=old).update(status=new)


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0003_commissionrequest_assigned_lab_user_and_more"),
        ("equipment", "0003_alter_equipment_status"),
        ("experiments", "0001_initial"),
        ("wip", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="wipbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("ready_for_dispatch", "Ready for Dispatch"),
                    ("dispatching", "Dispatching"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="DispatchQueueProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("proposal_no", models.CharField(max_length=32, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=40,
                    ),
                ),
                ("source", models.CharField(default="auto", max_length=40)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("note", models.TextField(blank=True)),
                ("estimated_total_runtime_sec", models.PositiveIntegerField(default=0)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_wip_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_wip_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dispatch_queue_proposal",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DispatchQueueProposalBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("compatibility_key", models.CharField(max_length=255)),
                ("estimated_runtime_sec", models.PositiveIntegerField(default=0)),
                ("reason", models.TextField(blank=True)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposal_batches",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "equipment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposal_batches",
                        to="equipment.equipmenttype",
                    ),
                ),
                (
                    "experiment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposal_batches",
                        to="experiments.experimenttype",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="wip.dispatchqueueproposal",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposal_batches",
                        to="equipment.recipe",
                    ),
                ),
            ],
            options={
                "db_table": "dispatch_queue_proposal_batch",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="DispatchQueueProposalItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("reason", models.TextField(blank=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="wip.dispatchqueueproposalbatch",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposal_items",
                        to="commissions.commissionrequest",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposal_items",
                        to="commissions.sample",
                    ),
                ),
            ],
            options={
                "db_table": "dispatch_queue_proposal_item",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dispatchqueueproposal",
            index=models.Index(
                fields=["status", "created_at"], name="dispatch_qu_status_7a6737_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dispatchqueueproposalitem",
            unique_together={("batch", "sample")},
        ),
        migrations.RunPython(migrate_wip_statuses, migrations.RunPython.noop),
    ]
