# Generated by Django 6.0.3 on 2026-05-23 08:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commissions", "0001_initial"),
        ("equipment", "0001_initial"),
        ("experiments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WipBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("wip_no", models.CharField(max_length=32, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("ready_for_dispatch", "Ready for Dispatch"),
                            ("queued", "Queued"),
                            ("dispatched", "Dispatched"),
                            ("running", "Running"),
                            ("partially_completed", "Partially Completed"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="created",
                        max_length=40,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("compatibility_key", models.CharField(max_length=255)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_wip_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wips",
                        to="equipment.equipmenttype",
                    ),
                ),
                (
                    "experiment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wips",
                        to="experiments.experimenttype",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wips",
                        to="equipment.recipe",
                    ),
                ),
            ],
            options={
                "db_table": "wip_batch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WipItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=40,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wip_items",
                        to="commissions.commissionrequest",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wip_items",
                        to="commissions.sample",
                    ),
                ),
                (
                    "wip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="wip.wipbatch",
                    ),
                ),
            ],
            options={
                "db_table": "wip_item",
                "ordering": ["sequence", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="WipStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("previous_status", models.CharField(blank=True, max_length=40)),
                ("new_status", models.CharField(max_length=40)),
                ("reason", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="wip.wipbatch",
                    ),
                ),
            ],
            options={
                "db_table": "wip_status_history",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="wipbatch",
            index=models.Index(
                fields=["status", "priority"], name="wip_batch_status_d6edec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wipbatch",
            index=models.Index(
                fields=["experiment_type", "recipe", "status"],
                name="wip_batch_experim_1f8325_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wipitem",
            unique_together={("wip", "sample")},
        ),
    ]
